# Generated by Django 3.1.7 on 2021-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='check_interval',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
