# Generated by Django 3.1.7 on 2021-03-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interval', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.interval')),
            ],
        ),
        migrations.DeleteModel(
            name='CeleryResult',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
