# Generated by Django 3.1.7 on 2021-03-13 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210313_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 3, 13, 15, 19, 25, 929905, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
    ]
