# Generated by Django 3.1.7 on 2021-03-20 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210315_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 10, 58, 46, 684412, tzinfo=utc)),
        ),
    ]
