# Generated by Django 3.1.7 on 2021-03-20 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210320_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 11, 2, 11, 173817, tzinfo=utc)),
        ),
    ]
